#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.98.113.123:3306/shareoffice?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
#  application:
#    name: provider_user
#server:
#  port: 8090

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.19.198:8756/eureka/  #注册中心地址
#  instance:
#    hostname: 192.168.19.198
#    instance-id: http://192.168.19.198:8081
spring:
    datasource:
        name: shareoffice
        url: jdbc:mysql://47.98.113.123:3306/shareoffice?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
       multipart:
         max-file-size: 100Mb
         max-request-size: 100Mb
    application:
      name: provider_user
mybatis:
  mapper-locations: classpath:mybatis/*.xml
#  type-aliases-package: cn.provider.entity
eureka:
  client:
    service-url:
      defaultZone: http://192.168.19.198:8756/eureka/  #注册中心地址
  instance:
    hostname: 192.168.19.198
    instance-id: http://192.168.19.198:8081
server:
  port: 8081